### ISSUE TITLE
Unexpected behaviour of the sorting functionality on the page Community Detection

### ISSUE THREAD

**Issue by MarleneID** [rwth-acis/OCD-Web-Client#19]
The sorting functionality on the page Community Dection of the Web Client is somehow mixed up. 
When clicking on _Name_ or _Creation_ in the head of the table, the entries are sorted by the graph's name. 
When sorting by the column _Graph_, the entries are sorted by _Name_. 
When sorting by _communities_, the entries are sorted by _Creation method_. 

Another strange behavoir is that when there are at least 2 pages of detected communties on this site, sorting the covers bei any column only sorts the entries on the site you are currently on. In other word, the sorting functionality ignores entries which are not on the current visible page. It would be nice if all entries in this list regardless of their location are consider when sorting the entries.

**Comment by MaxKissgen** [comment]
Created own issue for the second paragraph of this with #20 as it is not necessarily a bug (even though bad). Therefore, this current issue will be closed when the first mentioned problem is taken care of.
