### ISSUE TITLE
Dependency Management

### ISSUE THREAD

**Issue by istvank** [rwth-acis/OCD-Web-Client#2]
Some kind of dependency management would be great, like npm. Currently, libraries are pasted in into the JS directory, it seems.

**Comment by pedela** [comment]
Did I hear Bower?

**Comment by dmonad** [comment]
Hey guys, there is this new thing that we should use. Let me know if you need more info!

**Comment by pedela** [comment]
#feelsLikeFriday

**Comment by dmonad** [comment]
Just kiddin' ^^

**Comment by MaxKissgen** [comment]
With commit 4a4d91b0b97ee7d1c495ca0ef17551aa1c85feaf , this should now be solved. Dependency management is done with npm.
