### ISSUE TITLE
Make the graph table in the import page sortable

### ISSUE THREAD

**Issue by RuizhangZhou** [rwth-acis/OCD-Web-Client#45]
The graph table in the graphs.html and import.html are almost same. And the graphs in the graphs.html can be sorted according to the name or nodes(edges) count. But that in the import.html seems to also have this function, but it doesn't work now according to some bugs, need to be fixed
![thumb-Clipboard - 12  Juni 2022 16_33](https://user-images.githubusercontent.com/61236833/173314663-33ba36ba-8565-4fcc-8b49-43170e75c35d.png)
.

**Comment by MaxKissgen** [comment]
Fixed by #46 (Merge #47 for develope)
